include_guard(GLOBAL)

set(VE_EDITOR_COMMON_SOURCES
    Editor/Core/Editor.cpp
    Editor/Core/Editor.h
    Editor/Core/EditorAssetDatabase.cpp
    Editor/Core/EditorAssetDatabase.h
    Editor/Core/EditorAssetPath.cpp
    Editor/Core/EditorAssetPath.h
    Editor/Core/EditorBuildPackageDialog.cpp
    Editor/Core/EditorBuildPackageDialog.h
    Editor/Core/EditorBuiltinResources.cpp
    Editor/Core/EditorBuiltinResources.h
    Editor/Core/EditorEventDispatcher.h
    Editor/Core/EditorEvents.h
    Editor/Core/EditorInput.cpp
    Editor/Core/EditorInput.h
    Editor/Core/EditorInputBackend.h
    Editor/Core/EditorProject.cpp
    Editor/Core/EditorProject.h
    Editor/Core/EditorProjectDirectoryDialog.cpp
    Editor/Core/EditorProjectDirectoryDialog.h
    Editor/Core/EditorProjectEditingView.cpp
    Editor/Core/EditorProjectEditingView.h
    Editor/Core/EditorProjectPacker.cpp
    Editor/Core/EditorProjectPacker.h
    Editor/Core/EditorProjectRegistry.cpp
    Editor/Core/EditorProjectRegistry.h
    Editor/Core/EditorProjectRegistryBackend.h
    Editor/Core/EditorProjectSelectionView.cpp
    Editor/Core/EditorProjectSelectionView.h
    Editor/Core/EditorRenderBackend.h
    Editor/Core/EditorResourceLoader.cpp
    Editor/Core/EditorResourceLoader.h
    Editor/Core/EditorScriptCompiler.cpp
    Editor/Core/EditorScriptCompiler.h
    Editor/Core/EditorScriptDatabase.cpp
    Editor/Core/EditorScriptDatabase.h
    Editor/Core/EditorScriptProjectGenerator.cpp
    Editor/Core/EditorScriptProjectGenerator.h
    Editor/Core/EditorToolchain.cpp
    Editor/Core/EditorToolchain.h
    Editor/Core/Gizmos.cpp
    Editor/Core/Gizmos.h
    Editor/Panels/AssetsPanel.cpp
    Editor/Panels/AssetsPanel.h
    Editor/Panels/BasePanel.cpp
    Editor/Panels/BasePanel.h
    Editor/Panels/GameViewPanel.cpp
    Editor/Panels/GameViewPanel.h
    Editor/Panels/HierarchyPanel.cpp
    Editor/Panels/HierarchyPanel.h
    Editor/Panels/InspectorPanel.cpp
    Editor/Panels/InspectorPanel.h
    Editor/Panels/SceneViewPanel.cpp
    Editor/Panels/SceneViewPanel.h
    Editor/RenderPass/EditorGizmoRenderPass.cpp
    Editor/RenderPass/EditorGizmoRenderPass.h
    Editor/RenderPass/SceneGridRenderPass.cpp
    Editor/RenderPass/SceneGridRenderPass.h
)

function(ve_add_editor_packaging_definitions target_name)
    target_compile_definitions(${target_name}
        PRIVATE
            VE_PROJECT_SOURCE_DIR="${PROJECT_SOURCE_DIR}"
            VE_CMAKE_BINARY_DIR="${CMAKE_BINARY_DIR}"
            VE_CMAKE_BUILD_CONFIG="$<CONFIG>"
    )
endfunction()
