include_guard(GLOBAL)

include(CMake/Targets/Applications/Common.cmake)
include(CMake/Targets/Applications/Windows.cmake)
include(CMake/Targets/Applications/Mac.cmake)
include(CMake/Targets/Applications/IOS.cmake)

function(ve_add_player)
    if(NOT VE_BUILD_PLAYER)
        return()
    endif()

    if(WIN32)
        ve_add_windows_player()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        ve_add_ios_player()
    elseif(APPLE)
        ve_add_mac_player()
    endif()
endfunction()

function(ve_add_editor)
    if(NOT VE_BUILD_EDITOR)
        return()
    endif()

    if(WIN32)
        ve_add_windows_editor()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        return()
    elseif(APPLE)
        ve_add_mac_editor()
    endif()
endfunction()
