include_guard(GLOBAL)

include(CMake/Targets/Tests/MemoryTests.cmake)
include(CMake/Targets/Tests/MathTests.cmake)
include(CMake/Targets/Tests/ViewportTests.cmake)
include(CMake/Targets/Tests/ResourceRenderTests.cmake)
include(CMake/Targets/Tests/JoltIntegrationTests.cmake)
include(CMake/Targets/Tests/VirtualShadowTests.cmake)

function(ve_add_tests)
    if(NOT VE_BUILD_TESTS)
        return()
    endif()

    if(NOT WIN32)
        message(STATUS "VEngine unit tests are only built on Windows in the first stage.")
        return()
    endif()

    ve_add_memory_tests()
    ve_add_math_tests()
    ve_add_viewport_tests()
    ve_add_resource_render_tests()
    ve_add_jolt_integration_tests()
    ve_add_virtual_shadow_tests()
endfunction()
